version: '3.8'

services:
  backend-service:
    image: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    # depends_on:
    #   - mongodb

  frontend-service:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # mongodb:
  #   image: mongo:6.0
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #     - MONGO_INITDB_DATABASE=aviation_db
  #   volumes:
  #     - mongodb_data:/data/db

# volumes:
#   mongodb_data: