apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aviation.ai
  namespace: argocd
spec:
  project: aviation.ai.backend
  
  source:
    repoURL: https://github.com/bajaj-varun/aviation-ai-platform.git
    targetRevision: main
    path: kubernetes/deployment/backend
  
  destination:
    server: https://kubernetes.default.svc
    namespace: aviation.ai
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
    
  # Manual approval for production
  # syncWindows:
  # - kind: allow
  #   schedule: '0 9 * * 1-5'
  #   duration: 8h
  #   applications:
  #   - aviation-production