apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aviation.ai                
  namespace: argocd             
spec:
  project: aviation.ai.backend              
  source:
    repoURL: https://github.com/bajaj-varun/aviation-ai-platform.git   
    targetRevision: main        
    path: kubernetes/deployment/backend   

  project: aviation.ai.frontend              
  source:
    repoURL: https://github.com/bajaj-varun/aviation-ai-platform.git   
    targetRevision: main        
    path: kubernetes/deployment/frontend
       
  destination:
    server: https://kubernetes.default.svc  
    namespace: aviation.ai             
  syncPolicy:
    automated:
      prune: true                 
      selfHeal: true              