apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aviation.ai                
  namespace: argocd             
spec:
  project: aviation.ai              
  source:
    repoURL: https://github.com/bajaj-varun/aviation-ai-platform.git   
    targetRevision: main        
    path: kubernetes/deployments

  destination:
    server: https://kubernetes.default.svc  
    namespace: aviation-platform             
  syncPolicy:
    automated:
      prune: true                 
      selfHeal: true  
    syncOptions:
    - CreateNamespace=true            