apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: aviation-platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
    - job_name: 'aviation-backend'
      static_configs:
      - targets: ['backend-service:8000']
      metrics_path: /metrics
      
    - job_name: 'aviation-frontend'
      static_configs:
      - targets: ['frontend-service:80']
      metrics_path: /metrics

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: aviation-platform
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: LoadBalancer