apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aviation-development
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/bajaj-varun/aviation-ai-platform.git
    targetRevision: main
    path: kubernetes/infrastructure/overlays/development
    # directory:
    #   recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    
  # ignoreDifferences:
  # - group: apps
  #   kind: Deployment
  #   jsonPointers:
  #   - /spec/replicas