apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # - ../../../base/

images:
  - name: bajajv/aviation-backend
    newTag: main
  - name: bajajv/aviation-frontend
    newTag: main

configMapGenerator:
  - name: aviation-config
    namespace: aviation-platform
    behavior: merge
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO

# patchesStrategicMerge:
#   - deployment-patch.yaml